# 2015.11.18 12:04:30 Støední Evropa (bìžný èas)
# Embedded file name: scripts/common/Lib/lib-tk/Tkconstants.py
NO = FALSE = OFF = 0
YES = TRUE = ON = 1
N = 'n'
S = 's'
W = 'w'
E = 'e'
NW = 'nw'
SW = 'sw'
NE = 'ne'
SE = 'se'
NS = 'ns'
EW = 'ew'
NSEW = 'nsew'
CENTER = 'center'
NONE = 'none'
X = 'x'
Y = 'y'
BOTH = 'both'
LEFT = 'left'
TOP = 'top'
RIGHT = 'right'
BOTTOM = 'bottom'
RAISED = 'raised'
SUNKEN = 'sunken'
FLAT = 'flat'
RIDGE = 'ridge'
GROOVE = 'groove'
SOLID = 'solid'
HORIZONTAL = 'horizontal'
VERTICAL = 'vertical'
NUMERIC = 'numeric'
CHAR = 'char'
WORD = 'word'
BASELINE = 'baseline'
INSIDE = 'inside'
OUTSIDE = 'outside'
SEL = 'sel'
SEL_FIRST = 'sel.first'
SEL_LAST = 'sel.last'
END = 'end'
INSERT = 'insert'
CURRENT = 'current'
ANCHOR = 'anchor'
ALL = 'all'
NORMAL = 'normal'
DISABLED = 'disabled'
ACTIVE = 'active'
HIDDEN = 'hidden'
CASCADE = 'cascade'
CHECKBUTTON = 'checkbutton'
COMMAND = 'command'
RADIOBUTTON = 'radiobutton'
SEPARATOR = 'separator'
SINGLE = 'single'
BROWSE = 'browse'
MULTIPLE = 'multiple'
EXTENDED = 'extended'
DOTBOX = 'dotbox'
UNDERLINE = 'underline'
PIESLICE = 'pieslice'
CHORD = 'chord'
ARC = 'arc'
FIRST = 'first'
LAST = 'last'
BUTT = 'butt'
PROJECTING = 'projecting'
ROUND = 'round'
BEVEL = 'bevel'
MITER = 'miter'
MOVETO = 'moveto'
SCROLL = 'scroll'
UNITS = 'units'
PAGES = 'pages'
# okay decompyling c:\Users\PC\wotsources\files\originals\res_bw\scripts\common\lib\lib-tk\tkconstants.pyc 
# decompiled 1 files: 1 okay, 0 failed, 0 verify failed
# 2015.11.18 12:04:30 Støední Evropa (bìžný èas)
